# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\",\n\x04Item\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1b\n\x05items\x18\x02 \x03(\x0b\x32\x0c.orders.Item\x12\x16\n\x0epayment_method\x18\x03 \x01(\t\"1\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2J\n\x0cOrderService\x12:\n\x0b\x43reateOrder\x12\x14.orders.OrderRequest\x1a\x15.orders.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=24
  _globals['_ITEM']._serialized_end=68
  _globals['_ORDERREQUEST']._serialized_start=70
  _globals['_ORDERREQUEST']._serialized_end=154
  _globals['_ORDERRESPONSE']._serialized_start=156
  _globals['_ORDERRESPONSE']._serialized_end=205
  _globals['_ORDERSERVICE']._serialized_start=207
  _globals['_ORDERSERVICE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
