// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingRequest) Reset() {
	*x = ShippingRequest{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRequest) ProtoMessage() {}

func (x *ShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRequest.ProtoReflect.Descriptor instead.
func (*ShippingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShippingRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShippingId    string                 `protobuf:"bytes,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingResponse) Reset() {
	*x = ShippingResponse{}
	mi := &file_proto_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingResponse) ProtoMessage() {}

func (x *ShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingResponse.ProtoReflect.Descriptor instead.
func (*ShippingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingResponse) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

func (x *ShippingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_shipping_shipping_proto protoreflect.FileDescriptor

const file_proto_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/shipping/shipping.proto\x12\bshipping\"A\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"P\n" +
	"\x0fShippingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.shipping.ItemR\x05items\"K\n" +
	"\x10ShippingResponse\x12\x1f\n" +
	"\vshipping_id\x18\x01 \x01(\tR\n" +
	"shippingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2Z\n" +
	"\x0fShippingService\x12G\n" +
	"\x0eCreateShipment\x12\x19.shipping.ShippingRequest\x1a\x1a.shipping.ShippingResponseB\x1aZ\x18/proto/shipping;shippingb\x06proto3"

var (
	file_proto_shipping_shipping_proto_rawDescOnce sync.Once
	file_proto_shipping_shipping_proto_rawDescData []byte
)

func file_proto_shipping_shipping_proto_rawDescGZIP() []byte {
	file_proto_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_proto_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipping_shipping_proto_rawDesc), len(file_proto_shipping_shipping_proto_rawDesc)))
	})
	return file_proto_shipping_shipping_proto_rawDescData
}

var file_proto_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_shipping_shipping_proto_goTypes = []any{
	(*Item)(nil),             // 0: shipping.Item
	(*ShippingRequest)(nil),  // 1: shipping.ShippingRequest
	(*ShippingResponse)(nil), // 2: shipping.ShippingResponse
}
var file_proto_shipping_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.ShippingRequest.items:type_name -> shipping.Item
	1, // 1: shipping.ShippingService.CreateShipment:input_type -> shipping.ShippingRequest
	2, // 2: shipping.ShippingService.CreateShipment:output_type -> shipping.ShippingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shipping_shipping_proto_init() }
func file_proto_shipping_shipping_proto_init() {
	if File_proto_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipping_shipping_proto_rawDesc), len(file_proto_shipping_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_proto_shipping_shipping_proto_depIdxs,
		MessageInfos:      file_proto_shipping_shipping_proto_msgTypes,
	}.Build()
	File_proto_shipping_shipping_proto = out.File
	file_proto_shipping_shipping_proto_goTypes = nil
	file_proto_shipping_shipping_proto_depIdxs = nil
}
