// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/mom.proto

package mom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MomService_ProcessAllPending_FullMethodName = "/mom.MomService/ProcessAllPending"
)

// MomServiceClient is the client API for MomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MomServiceClient interface {
	ProcessAllPending(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MomSummary, error)
}

type momServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMomServiceClient(cc grpc.ClientConnInterface) MomServiceClient {
	return &momServiceClient{cc}
}

func (c *momServiceClient) ProcessAllPending(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MomSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MomSummary)
	err := c.cc.Invoke(ctx, MomService_ProcessAllPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MomServiceServer is the server API for MomService service.
// All implementations must embed UnimplementedMomServiceServer
// for forward compatibility.
type MomServiceServer interface {
	ProcessAllPending(context.Context, *emptypb.Empty) (*MomSummary, error)
	mustEmbedUnimplementedMomServiceServer()
}

// UnimplementedMomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMomServiceServer struct{}

func (UnimplementedMomServiceServer) ProcessAllPending(context.Context, *emptypb.Empty) (*MomSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAllPending not implemented")
}
func (UnimplementedMomServiceServer) mustEmbedUnimplementedMomServiceServer() {}
func (UnimplementedMomServiceServer) testEmbeddedByValue()                    {}

// UnsafeMomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MomServiceServer will
// result in compilation errors.
type UnsafeMomServiceServer interface {
	mustEmbedUnimplementedMomServiceServer()
}

func RegisterMomServiceServer(s grpc.ServiceRegistrar, srv MomServiceServer) {
	// If the following call pancis, it indicates UnimplementedMomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MomService_ServiceDesc, srv)
}

func _MomService_ProcessAllPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomServiceServer).ProcessAllPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomService_ProcessAllPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomServiceServer).ProcessAllPending(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MomService_ServiceDesc is the grpc.ServiceDesc for MomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mom.MomService",
	HandlerType: (*MomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAllPending",
			Handler:    _MomService_ProcessAllPending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mom.proto",
}
